# Generated by Django 3.2.9 on 2021-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='назване мероприятия')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('data', models.DateField(verbose_name='дата мероприятия')),
                ('time', models.TimeField(verbose_name='время мероприятия')),
                ('photo', models.ImageField(upload_to='activity.static', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
