# Generated by Django 3.2.9 on 2021-11-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='назване блюда')),
                ('weight', models.CharField(max_length=20, verbose_name='вес блюда')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('price', models.CharField(max_length=10, verbose_name='цена')),
                ('photo', models.ImageField(upload_to='', verbose_name='фото')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.categories', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
