# Generated by Django 3.2.9 on 2021-11-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.IntegerField(choices=[(1, 'Супы'), (2, 'Салаты'), (3, 'Основные'), (4, 'Закуски'), (5, 'Десерты')], verbose_name='категория')),
                ('name', models.CharField(max_length=50, verbose_name='назване блюда')),
                ('weight', models.CharField(max_length=20, verbose_name='вес блюда')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('price', models.CharField(max_length=10, verbose_name='цена')),
                ('photo', models.ImageField(upload_to='menu.static', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
