# Generated by Django 3.2.9 on 2021-11-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, verbose_name='фамилия')),
                ('phone', models.CharField(max_length=13, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('date', models.DateField(verbose_name='дата')),
                ('time', models.TimeField(verbose_name='время')),
                ('people', models.IntegerField(verbose_name='количество человек')),
                ('table', models.IntegerField(blank=True, null=True, verbose_name='номер стола')),
            ],
            options={
                'verbose_name': 'бронь',
                'verbose_name_plural': 'брони',
            },
        ),
    ]
